### ISSUE TITLE
Multiple Where clauses not working?

### ISSUE THREAD

**Issue by Dwebtron** [ImangazalievM/ReActiveAndroid#39]
ReActiveAndroid Version: 1.4.3

Bug or Feature Request: Multiple WHERE clauses in query

Description: I'm trying to migrate from ActiveAndroid to REActiveAndroid but having some problems with multiple WHERE clause migrations. 

The old way to do it in AA was like:
    ` Note note = Select.from(Note.class).where("noteId = ?", username).where("noteContent= ?", content).fetchSingle();
`

Now, according to this migration guide: https://imangazalievm.gitbooks.io/reactiveandroid/migration-from-activeandroid.html we're supposed to do it this way:
```
List<Note> notes = Select.from(Note.class).fetch();
List<Note> notes = Select.from(Note.class).execute();
Note note = Select.from(Note.class).where("id=? AND title LIKE '?%'", 1, "Hello").fetchSingle();
```

There's several problems with this. First, "notes" is defined twice, Second ".execute();" cannot be resolved by Android Studio, and third (and perhaps most importantly) when I build it like the tutorial states, I get:
`    java.lang.IllegalArgumentException: Cannot bind argument at index 2 because the index is out of range.  The statement has 1 parameters.
`

Why this change? What should I do to fix it?

**Comment by ImangazalievM** [comment]
1. This sample is not correct:

```java
List<Note> notes = Select.from(Note.class).execute();
```

I removed it from the documentation.

2. ReActiveAndroid has a different syntax for building `SELECT` queries with `WHERE' clause. The sample in the documentation was incorrect and I fixed it. The correct version of the query:

```java
Note note = Select.from(Note.class).where("id=? AND title LIKE '?%'", 1, "Hello").fetchSingle();
```

Thanks for your report!

**Comment by bhapps** [comment]
There is still an issue where I wish to return all (or paginated) data filtered by the query using `fetch()` which returns the error of `Cannot bind argument at index 2 because the index is out of range. The statement has 1 parameters`

All the documentation advises only of using  `fetchSingle()` when using multiple `Where clauses`
I wish not to return only the first hit, but all (or some) data items.

Maybe `fetch()` has not been implemented for using multiple `Where clauses`

**Comment by cviacmob** [comment]
How to use single column to get multiple value based on filter , given below code error . kindly solve this query
Select.from(SeasonMasterDB.class).where("state LIKE '%" + "current_season" +"old_season"+ "%'").fetchSingle();
